include:
- 01_iot_data_producer/target/iot-kafka-producer-1.0.0-jar-with-dependencies.jar
kind: ArchiveUploadSpec
name: iot-kafka-producer-1-0-0-jar

---
apiVersion: fission.io/v1
kind: Package
metadata:
  creationTimestamp: null
  name: iot-kafka-producer-1-0-0-jar-rrvv
  namespace: default
spec:
  deployment:
    checksum: {}
    type: url
    url: archive://iot-kafka-producer-1-0-0-jar
  environment:
    name: java
    namespace: default
  source:
    checksum: {}
status:
  buildstatus: none